#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry="0"
platform=""

while [[ $# > 0 ]]; do
	if [[ $1 == "--dry" ]]; then
		dry="1"
	elif [[ $1 == "--platform" ]]; then
		shift
		platform="$1"
	else
		filter="$1"
	fi
	shift
done

if [[ "$platform" != "mac" && "$platform" != "linux" ]]; then
	echo "Error: --platform is required and must be 'mac' or 'linux'" >&2
	exit 1
fi

export PLATFORM="$platform"

log() {
	if [[ $dry == "1" ]]; then
	    	echo "[DRY RUN]: $@"
	else
		echo "$@"
	fi
}

execute() {
	log "execute: $@"
	if [[ $dry == "1" ]]; then
		return
	fi
	"$@"
}

log "$script_dir -- $filter"

cd $script_dir

# +111 executable by anybody +100 for user
scripts=$(find ./runs -maxdepth 1 -mindepth 1 -perm +111 -type f)
# scripts=$(find ./runs -maxdepth 1 -mindepth 1 -perm +111 -type f; find ./runs/libs -maxdepth 1 -mindepth 1 -perm +111 -type f)

for script in $scripts; do
	if echo "$script" | grep -qv "$filter"; then
		log "filtered: $filter : $script"
		continue
	
	fi

	execute ./$script
done
