#!/usr/bin/env bash

if [[ "$PLATFORM" == "linux" ]]; then
    echo "skipped: ghostty (mac only)"
    exit 0
fi

if ! command -v ghostty &> /dev/null && [[ ! -d /Applications/Ghostty.app ]]; then
    brew install --cask ghostty
else
    echo "Ghostty already installed"
fi
