#!/usr/bin/env bash

if ! command -v nvim &> /dev/null; then
    echo "Installing Neovim..."
    if [[ "$PLATFORM" == "mac" ]]; then
        brew install neovim
    elif [[ "$PLATFORM" == "linux" ]]; then
        sudo snap install nvim --classic
    fi
    echo "Neovim has been installed successfully!"
else
    echo "Neovim is already installed"
fi

nvim --version