#!/usr/bin/env bash

if ! command -v rg &> /dev/null; then
    if [[ "$PLATFORM" == "mac" ]]; then
        brew install ripgrep
    elif [[ "$PLATFORM" == "linux" ]]; then
        sudo apt install -y ripgrep
    fi
else
    echo "ripgrep already installed"
fi
