#!/usr/bin/env bash
if ! command -v zsh &> /dev/null; then
        echo "Zsh not installed. Installing..."
        brew install zsh
        chsh -s $(which zsh)
fi

if [ ! -d "$HOME/.oh-my-zsh" ]; then
        echo "Installing Oh My Zsh..."
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
        echo "Oh My Zsh is already installed."
fi
