set -g default-terminal "tmux-256color"
set -s escape-time 0
set -g base-index 1

unbind C-b
set-option -g prefix C-g
bind-key C-g send-prefix

# vi key movement for copy/pasta mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind | split-window -h
bind v split-window -v
bind - split-window -v

set -g mouse on
set -g history-limit 50000
