#!/usr/bin/env bash
selected=$(find ~/repos -mindepth 1 -maxdepth 2 -type d | fzf)
if [[ -z "$selected" ]]; then
    exit 0
fi
selected_name=$(basename $selected | tr ".,: " "____")

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z "$TMUX" ]]; then
    tmux attach-session -t $selected_name \; send-keys "ready-tmux" Enter 
else
    tmux switch-client -t $selected_name
    tmux send-keys -t $selected_name "ready-tmux" Enter
fi
